Add lat long to the public api
DFE-Digital/teacher-training-api pull request #1671
Opened 2020-12-01 10:37 UTC by davidgisbey

### Context

We're now using the public API so I've close the other PR, added lat/long here and updated the docs accordingly.

### Changes proposed in this pull request

- Add lat & long to the provider serialiser
- Update docs and tests
 
### Guidance to review

Is that everything that needs to be done @dankmitchell?

### Checklist

- [x] Make sure all information from the Trello card is in here
- [x] Attach to Trello card
- [x] Rebased master
- [x] Cleaned commit history
- [x] Tested by running locally

2020-12-02 07:19 UTC, gpeng requested changes
Thanks for adding this @davidgisbey. The docs need updating here -> https://github.com/DFE-Digital/teacher-training-api/blob/master/swagger/public_v1/component_schemas/ProviderAttributes.yml

2020-12-02 10:20 UTC, davidgisbey commented
Thanks for pointing me in the right direction Graham

2020-12-03 16:01 UTC, TobyRet approved these changes

2020-12-03 18:06 UTC, defong approved these changes
You may need to update swagger/public_v1/api_spec.json as well

2020-12-04 11:55 UTC, gpeng requested changes

2020-12-04 11:55 UTC, gpeng commented on swagger/public_v1/component_schemas/ProviderAttributes.yml
> +    description: "The latitude of the provider's address"
```suggestion
    description: "The longitude of the provider's address"
```

2020-12-04 13:10 UTC, merged