[755] Clean up include examples for public api end points
DFE-Digital/teacher-training-api pull request #1716
Opened 2021-01-08 09:53 UTC by darokel

### Context

- https://trello.com/c/Hpj3nXtX/755-m-refactor-include-schema-definition-setup

### Changes proposed in this pull request

- Refactors some of the documented public endpoint examples to correctly show their relationships/include options
- Previously, any endpoint with an optional include query parameter would return a random `Resource` defined in the swagger template, this change makes it more explicit what to render in that file.

### Guidance to review

- Fire up the API docs locally
- Assert any endpoint with optional includes shows the correct structure in the response example

### Checklist

- [x] Make sure all information from the Trello card is in here
- [x] Attach to Trello card
- [x] Rebased master
- [x] Cleaned commit history
- [x] Tested by running locally

2021-01-08 10:10 UTC, darokel commented
![](https://github.trello.services/images/mini-trello-icon.png) [[M] Refactor include schema definition setup](https://trello.com/c/Hpj3nXtX/755-m-refactor-include-schema-definition-setup)

2021-01-12 09:59 UTC, gpeng approved these changes
This looks good to me. Can we get @defong to review before we merge though just to be on the safe side.

2021-01-12 16:28 UTC, defong requested changes
The structure looks rightish... but they also looks 

- bit part

![image](https://user-images.githubusercontent.com/470137/104341843-2553cd80-54f2-11eb-974d-523b1a010aa6.png)

- half filled 

![image](https://user-images.githubusercontent.com/470137/104342859-33eeb480-54f3-11eb-9c3a-53db544a2042.png)



Missing example for bad request?
![image](https://user-images.githubusercontent.com/470137/104341965-43213280-54f2-11eb-8465-d86981b32af8.png)

For this endpoint `/recruitment_cycles/{year}/providers/{provider_code}/courses `
the parameters does not match the examples

- parameters does not have `include`
- example has `included`

2021-01-15 09:21 UTC, darokel commented
@defong Pushed up the changes https://github.com/DFE-Digital/teacher-training-api/pull/1716. I removed the 400 as at the moment it does not return a response. We have a ticket somewhere to introduce a generic error handling method which may make sense to use at that point and update this but out of scope for this ticket.

2021-01-15 11:48 UTC, defong approved these changes
> This looks good to me. Can we get @defong to review before we merge though just to be on the safe side.

toothcombed

spinoffs https://trello.com/c/x28JcW5k/874-api-docs-response-examples-are-wrong @gpeng

2021-01-15 11:48 UTC, defong commented on swagger/public_v1/component_schemas/CourseRelationships.yml
> +    $ref: "#/components/schemas/Relationship"
new line

2021-01-15 14:03 UTC, merged