[851] Add `changed_since` filter option for /api/public/v1/courses
DFE-Digital/teacher-training-api pull request #1736
Opened 2021-01-21 16:48 UTC by jhenderson

### Context
https://trello.com/c/eQnKyAgV/851-s-filter-by-updatedsince-on-api-public-v1-courses-endpoint-update-tech-notes-from-provider

### Changes proposed in this pull request
- Add `changed_since` filter scope to `CourseSearchService`
- Updated swagger doc spec

### Checklist

- [x] Make sure all information from the Trello card is in here
- [x] Attach to Trello card
- [x] Rebased master
- [x] Cleaned commit history
- [x] Tested by running locally

2021-01-21 16:50 UTC, jhenderson commented
![](https://github.trello.services/images/mini-trello-icon.png) [[S] Filter by updated_since on /api/public/v1/courses endpoint [update tech notes from provider]](https://trello.com/c/eQnKyAgV/851-s-filter-by-updatedsince-on-api-public-v1-courses-endpoint-update-tech-notes-from-provider)

2021-01-22 13:29 UTC, darokel approved these changes

2021-01-22 15:12 UTC, defong approved these changes

2021-01-22 15:12 UTC, defong commented on swagger/public_v1/component_schemas/CourseFilter.yml
> +    description: "Return courses that only have changed since date (ISO 8601 date format)"
```suggestion
    description: "Return courses that only have updated since date (ISO 8601 date format)"
```
Being petty

2021-01-25 09:41 UTC, gpeng requested changes

2021-01-25 09:41 UTC, gpeng commented on swagger/public_v1/component_schemas/CourseFilter.yml
> +    description: "Return courses that only have changed since date (ISO 8601 date format)"
I don't think this reads well.

```suggestion
    description: "Return courses have been updated since the date (ISO 8601 date format)"
```

2021-01-27 09:39 UTC, gpeng approved these changes

2021-01-27 09:50 UTC, merged