860 l filter by updatedsince on api public v1 providers endpoint
DFE-Digital/teacher-training-api pull request #1737
Opened 2021-01-21 16:48 UTC by defong

### Context
Public v1 provider endpoint filtering

### Changes proposed in this pull request
Allowing filtering based on providers `changed_at` date

### Guidance to review

- Api docs 
- actual endpoint
  - http://localhost:3001/api/public/v1/recruitment_cycles/2021/providers?filter[changed_since]=2020-11-13T11:21:55Z 

### Checklist

- [ ] Make sure all information from the Trello card is in here
- [ ] Attach to Trello card
- [ ] Rebased master
- [ ] Cleaned commit history
- [ ] Tested by running locally

2021-01-21 16:50 UTC, defong commented
![](https://github.trello.services/images/mini-trello-icon.png) [[L] Filter by updated_since on /api/public/v1/providers endpoint](https://trello.com/c/ZRKZuNDz/860-l-filter-by-updatedsince-on-api-public-v1-providers-endpoint)

2021-01-22 12:59 UTC, darokel approved these changes

2021-01-25 09:38 UTC, gpeng requested changes

2021-01-25 09:38 UTC, gpeng commented on swagger/public_v1/api_spec.json
> +            "description": "Return providers that only have updated since date (ISO 8601 date format)",
```suggestion
            "description": "Return providers that have been updated since the date (ISO 8601 date format)",
```

2021-01-25 09:38 UTC, gpeng commented on swagger/public_v1/component_schemas/ProviderFilter.yml
> +    description: "Return providers that only have updated since date (ISO 8601 date format)"
```suggestion
    description: "Return providers that have been updated since the date (ISO 8601 date format)"
```

2021-01-25 10:17 UTC, gpeng approved these changes

2021-01-25 11:02 UTC, merged