1317 add edit provider name feature to providers pages
DFE-Digital/teacher-training-api pull request #1850
Opened 2021-04-08 15:54 UTC by JonF1

### Context
https://trello.com/c/cwKSUfTf/1317-s-add-edit-provider-name-feature-to-providers-pages

### Changes proposed in this pull request
*Adds edit link next to provider form which takes user to form
*Uniqueness and length validations. I set 100 chars limit as no provider name is more than 80 chars 
*Feature test
### Guidance to review
Go to /support/providers and select a provider

### Checklist

- [ ] Make sure all information from the Trello card is in here
- [ ] Attach to Trello card
- [ ] Rebased master
- [ ] Cleaned commit history
- [ ] Tested by running locally

2021-04-08 15:56 UTC, JonF1 commented
![](https://github.trello.services/images/mini-trello-icon.png) [[S] Add "Edit provider name" feature to providers' pages](https://trello.com/c/cwKSUfTf/1317-s-add-edit-provider-name-feature-to-providers-pages)

2021-04-09 15:02 UTC, darokel commented on app/webpacker/styles/application.scss
> +}
line endings 🙈

2021-04-09 15:04 UTC, darokel reviewed
Looking good. I wonder if we should just follow this pattern to allow names to be changed:

<img width="1313" alt="Screenshot 2021-04-09 at 16 01 43" src="https://user-images.githubusercontent.com/616080/114200534-35424880-994d-11eb-9c3e-8138116817b8.png">

We should probably start populating this summary view in the details tab and show their name there with the change link to the right? This would match our pattern in register.

2021-04-12 11:11 UTC, JonF1 commented
> We should probably start populating this summary view in the details tab and show their name there with the change link to the right? This would match our pattern in register.

Ok I'll add blocked to the ticket

2021-04-13 15:38 UTC, JonF1 commented on app/webpacker/styles/application.scss
> +}
i fixed by removing all the css 😆

2021-04-14 09:00 UTC, darokel requested changes
Looking good. Left a couple of comments to get this over the line

2021-04-14 09:00 UTC, darokel commented on app/views/support/providers/edit.html.erb
> +</div>
line ending

2021-04-14 09:00 UTC, darokel commented on app/views/support/providers/show.html.erb
> +end %>
line ending

2021-04-14 09:00 UTC, darokel commented on app/views/support/providers/show.html.erb
> +    key: 'Name',
could we swap for double quotes

2021-04-14 09:00 UTC, darokel commented on app/webpacker/styles/application.scss
> +@import "~@ministryofjustice/frontend/moj/all";
line ending

2021-04-14 09:00 UTC, darokel commented on app/controllers/support/providers_controller.rb
> +    def last_updated_provider
this should go in a helper i think (and the included TimeFormat)

2021-04-14 13:38 UTC, darokel commented on app/helpers/support_time_helper.rb
> +module SupportTimeHelper
I think these helpers should be nested in a support directory to follow convention of other parts. `app/helpers/support/time_helper.rb` then you'd have:

```
module Support
  module TimeHelper
  end
end
```

2021-04-14 13:57 UTC, darokel approved these changes

2021-04-18 15:44 UTC, merged