Log skylight to STDOUT
DFE-Digital/teacher-training-api pull request #1885
Opened 2021-04-23 16:01 UTC by archferns

### Context

### Changes proposed in this pull request

### Guidance to review

### Checklist

- [ ] Make sure all information from the Trello card is in here
- [ ] Attach to Trello card
- [ ] Rebased master
- [ ] Cleaned commit history
- [ ] Tested by running locally

2021-04-23 16:17 UTC, archferns commented
![](https://github.trello.services/images/mini-trello-icon.png) [[Spike] [1/2 day] Investigate skylight error logs](https://trello.com/c/koeGOZEi/1579-spike-1-2-day-investigate-skylight-error-logs)

2021-04-26 08:55 UTC, defong approved these changes

2021-04-26 12:13 UTC, vigneshmsft requested changes
can we set this to `SemanticLogger[Skylight]`

2021-04-26 13:04 UTC, archferns commented
Will give that a try, off the top of my head skylight runs quite early in the stack, so we might need to require SemanticLogger earlier.

> can we set this to `SemanticLogger[Skylight]`

2021-04-27 10:15 UTC, vigneshmsft approved these changes

2021-04-27 10:48 UTC, merged