Add validation for visa sponsorship
DFE-Digital/teacher-training-api pull request #1981
Opened 2021-06-15 08:40 UTC by stevehook

### Context

Starting in the 2022 recruitment cycle we will require providers declare whether or not they can sponsor visas (student and skilled worker) before publishing any courses in that cycle. 

https://trello.com/c/I2K4fchq/3441-add-visa-flow-to-publish

### Changes proposed in this pull request

- [x] Add a new validation in the `Course` model to cover this requirement.
- [x] Add `Provider#visa_sponsorship_publishable?` as a helper method for the above validation.
- [x] Unit tests for `Provider#visa_sponsorship_publishable?` and controller spec to cover the API.

### Guidance to review

- Is there a better way to implement the specs for this?
- Are there any potential knock-on effects that might cause issues in the 2022 cycle?

### Checklist

- [x] Make sure all information from the Trello card is in here
- [x] Attach to Trello card
- [x] Rebased master
- [x] Cleaned commit history
- [ ] Tested by running locally

2021-06-18 08:28 UTC, davidgisbey commented on config/locales/en.yml
> +              visa_sponsorship_not_publishable: "You must say whether your provider can sponsor visas"
Should this be `You must say whether you can sponsor visas`

2021-06-18 09:03 UTC, defong requested changes
Has side affects
![image](https://user-images.githubusercontent.com/470137/122536397-63fb3000-d01c-11eb-8c3f-1bb151300925.png)

2021-06-18 09:03 UTC, defong commented on spec/models/provider_spec.rb
> +    it "returns true when year is 2022 and provider has declared sponsorship" do
lack context 

https://www.betterspecs.org/#contexts

2021-06-18 10:20 UTC, stevehook commented on spec/controllers/api/v2/courses_controller_spec.rb
> +    it "returns a validation error when visa sponsorship information is unpublishable" do
I've added a context for 2021 and 2022 - things don't change going any further forward.

2021-06-24 10:27 UTC, davidgisbey approved these changes
lgtm

2021-06-24 13:49 UTC, defong approved these changes
Let's get this moving!

2021-06-24 13:59 UTC, merged