Add qualification params to courses controller
DFE-Digital/teacher-training-api pull request #2011
Opened 2021-06-28 09:56 UTC by george-bit

### Context

As part of the work being carried out on the structured GCSE's on publish certain params
are not saving correctly to the database. On inspection this is due to the guard clause
on the update action of the controller. 

### Changes proposed in this pull request

This PR updates the method to include these params.

### Guidance to review

### Checklist

- [x] Make sure all information from the Trello card is in here
- [x] Attach to Trello card
- [x] Rebased master
- [x] Cleaned commit history
- [x] Tested by running locally

2021-06-29 13:24 UTC, avinhurry commented
This seems to be causing Sentry errors: https://sentry.io/organizations/dfe-bat/issues/2482806787/?environment=review&project=1377944&referrer=alert_email

2021-06-29 13:30 UTC, defong requested changes
Test?

2021-06-29 13:31 UTC, george-bit commented
Hey @avinhurry, error are coming from testing, my bad 😓 . The review apps aren't configured quite right yet so caused an error when I tried to go to a new cycle

Currently, working through with Graham.

2021-06-30 11:12 UTC, defong approved these changes

2021-06-30 11:14 UTC, merged