Add filter for courses whose provider can sponsor visas
DFE-Digital/teacher-training-api pull request #2128
Opened 2021-08-24 12:47 UTC by davidgisbey

### Context

One of the new features that we're adding to Find is the ability to filter courses based on whether the provider can offer either a skilled worker or student visa 

This PR adds in the functionality required to allow this.

### Changes proposed in this pull request

- Add a scope to the course model which returns providers who can sponsor a visa
- Add the scope to the course search service
- Tests 

### Checklist

- [x] Make sure all information from the Trello card is in here
- [x] Attach to Trello card
- [x] Rebased master
- [x] Cleaned commit history
- [x] Tested by running locally

2021-08-24 13:59 UTC, TobyRet commented on spec/requests/api/v3/courses/index_spec.rb
> +      it "is returns courses where the provider offers visas" do
Small grammar error `it "is returns`

2021-08-24 14:00 UTC, TobyRet commented on spec/services/course_search_service_spec.rb
> +        it "adds the with_send scope" do
`"adds the with_send scope"` ?

2021-08-24 14:01 UTC, TobyRet commented on app/models/course.rb
> +  scope :provider_can_sponsor_visa, -> do
Unit spec req'd

2021-08-24 14:01 UTC, TobyRet requested changes
Just a couple of minor changes required

2021-08-24 14:03 UTC, TobyRet commented
Just noticed docs need to be updated also ...
https://api.publish-teacher-training-courses.service.gov.uk/api-reference.html#schema-coursefilter

2021-08-24 14:48 UTC, davidgisbey commented on spec/services/course_search_service_spec.rb
> +        it "doesn't add the with_send scope" do
i may have done some copy pasting here 😬

2021-08-25 09:02 UTC, davidgisbey commented
Have actioned the changes 👍

2021-09-02 10:36 UTC, TobyRet approved these changes

2021-09-02 10:40 UTC, merged