[369] allow support users to edit confirmed allocation numbers
DFE-Digital/teacher-training-api pull request #2273
Opened 2021-11-11 16:29 UTC by stellenberger

### Context

- [This trello ticket](https://trello.com/c/GzEv6eFo/369-allow-support-users-to-edit-confirmed-allocation-numbers)

### Changes proposed in this pull request

- Add edit/update functionality to change allocation numbers on the Support console

### Guidance to review

- Go to the support console
- Click on the PE Allocations tab
- Choose a provider
- Click the Change link on the allocation number

### Checklist

- [x] Make sure all information from the Trello card is in here
- [x] Attach to Trello card
- [x] Rebased master
- [x] Cleaned commit history
- [x] Tested by running locally

2021-11-11 16:35 UTC, defong commented on spec/support/page_objects/support/allocations_index.rb
> +      end
why not `elements` or `sections`?

2021-11-11 17:19 UTC, stellenberger commented
![](https://github.trello.services/images/mini-trello-icon.png) [Allow support users to edit confirmed allocation numbers](https://trello.com/c/GzEv6eFo/369-allow-support-users-to-edit-confirmed-allocation-numbers)

2021-11-15 12:12 UTC, malcolmbaig requested changes
Leaving a note for @stellenberger — please double check with @mbocc if we still need this functionality.

2021-11-16 10:46 UTC, stellenberger commented
Closing this as feature no longer needed

2021-11-16 10:46 UTC, closed without merging