379 fix duplicate allocations
DFE-Digital/teacher-training-api pull request #2286
Opened 2021-11-17 12:42 UTC by stellenberger

### Context

- [This trello ticket](https://trello.com/c/baYPHa6j/379-duplicate-loughborough-learning-alliance-uni-of-derby-on-support-console)

### Changes proposed in this pull request

- Populate the allocations through the allocation model (rather than through Provider)
- Set up a separate filter for allocation
- Add supporting filter spec

### Guidance to review

### Checklist

- [x] Make sure all information from the Trello card is in here
- [x] Attach to Trello card
- [x] Rebased master
- [x] Cleaned commit history
- [x] Tested by running locally

2021-11-17 12:54 UTC, stellenberger commented
![](https://github.trello.services/images/mini-trello-icon.png) [Duplicate Loughborough Learning Alliance/Uni of Derby on support console](https://trello.com/c/baYPHa6j/379-duplicate-loughborough-learning-alliance-uni-of-derby-on-support-console)

2021-11-17 12:54 UTC, stellenberger commented
![](https://github.trello.services/images/mini-trello-icon.png) [Duplicate Woodrush Training Consortium/Uni of Warwick on support console](https://trello.com/c/lC1S4rP5/380-duplicate-woodrush-training-consortium-uni-of-warwick-on-support-console)

2021-11-18 10:43 UTC, defong requested changes
![image](https://user-images.githubusercontent.com/470137/142400627-9dbb0776-f460-4db0-98d6-b93c697e6e7e.png)

2021-11-19 10:30 UTC, defong approved these changes

2021-11-19 10:32 UTC, merged