[406] Change allocation table to use card-list
DFE-Digital/teacher-training-api pull request #2292
Opened 2021-11-22 17:35 UTC by stellenberger

### Context

- [This trello ticket](https://trello.com/c/1dIdEqIM/406-change-table-type-in-the-support-console-allocations-to-horizontal)

### Changes proposed in this pull request

- Flip table horizontally to use a carded list instead

### Guidance to review

- Log onto support console and go to the PE Allocations tab

### Checklist

- [x] Make sure all information from the Trello card is in here
- [x] Attach to Trello card
- [x] Rebased master
- [x] Cleaned commit history
- [x] Tested by running locally

2021-11-23 11:08 UTC, stellenberger commented
![](https://github.trello.services/images/mini-trello-icon.png) [Change table type in the support console allocations to horizontal](https://trello.com/c/1dIdEqIM/406-change-table-type-in-the-support-console-allocations-to-horizontal)

2021-11-23 11:31 UTC, defong requested changes

2021-11-23 11:31 UTC, defong commented on .rubocop_todo.yml
> +    - "app/components/allocation_record_card/view.rb"
If this is here is it inheriting of the wrong parent 

Maybe use `ViewComponent::Base` or it really needs `super`

2021-11-25 10:30 UTC, defong requested changes
view preview does not work

2021-11-25 10:30 UTC, defong commented on spec/components/allocation_record_card/view_preview.rb
> +    end
https://teacher-training-api-pr-2292.london.cloudapps.digital/view_components/allocation_record_card/view/multiple_cards

2021-11-25 10:30 UTC, defong commented on spec/components/allocation_record_card/view_preview.rb
> +    end
https://teacher-training-api-pr-2292.london.cloudapps.digital/view_components/allocation_record_card/view/single_card

2021-11-25 12:37 UTC, mbocc approved these changes
Amazing des skills - all looks good, all approved!

2021-11-25 13:43 UTC, defong approved these changes

2021-11-25 14:18 UTC, merged