Add About Your Organisation page
DFE-Digital/teacher-training-api pull request #2322
Opened 2021-12-07 09:38 UTC by malcolmbaig

### Context
This is the first section of Publish we're migrating across. 

https://trello.com/c/wlq5VfsQ

### Changes proposed in this pull request
Add the base page and all dependencies needed to render it. Subsequent PRs will implement the various sub-pages.

### Guidance to review
- Per commit is probably best
- Feature specs to follow later
- Can be tested locally by authenticating as a persona and navigating to `/publish/organisations/#{provider_code}/2022/details`

### Checklist

- [x] Make sure all information from the Trello card is in here
- [x] Attach to Trello card
- [ ] Rebased master
- [x] Cleaned commit history
- [x] Tested by running locally

2021-12-09 09:45 UTC, defong requested changes
We need to consider enforce returning what can be shown and the showing `actual` page

2021-12-14 16:58 UTC, malcolmbaig commented on app/views/publish_interface/providers/details.html.erb
> +<% content_for :page_title, title_with_error_prefix("About your organisation", @errors.present?) %>
Have fixed this in the next PR.

2021-12-14 16:59 UTC, malcolmbaig commented on app/controllers/publish_interface/providers_controller.rb
> +    rescue_from ActiveRecord::RecordNotFound, with: :not_found
Fixing now, there's a bunch of stuff that needs porting across as well to make these pages display properly.

2021-12-15 14:19 UTC, malcolmbaig commented on app/controllers/publish_interface/providers_controller.rb
> +    rescue_from ActiveRecord::RecordNotFound, with: :not_found
@defong got the fixes for these, but makes more sense for them to go in a separate PR. Will add you for review once they're up.

2021-12-15 14:20 UTC, defong commented on app/controllers/publish_interface/providers_controller.rb
> +    rescue_from ActiveRecord::RecordNotFound, with: :not_found
nice one

2021-12-15 14:20 UTC, defong approved these changes

2021-12-15 15:22 UTC, malcolmbaig commented on app/helpers/application_helper.rb
> +  # def pagy_govuk_nav(pagy)
Yeah this was a hunch I had about what would be easier over time as the migration progresses. Still not sure about it, but the reasoning was:

- If code in any of these helper classes or domain objects changes in Old Publish, it'll be easier to reconcile those changes with what we've copied across to New Publish if we take the whole file 
- We can delete any remaining commented (ie—unused) code at the end of the migration when we're cleaning up

Can always tidy up at any point during the migration if this becomes an issue for whatever reason?

2021-12-15 15:35 UTC, merged