[456] Write UserPermission and OrganisationUser concurrently
DFE-Digital/teacher-training-api pull request #2326
Opened 2021-12-08 10:21 UTC by stellenberger

### Context

- [This trello ticket](https://trello.com/c/rRlaSz79/456-dual-running-userpermission-along-with-organisation)

### Changes proposed in this pull request

- [ ] Fix broken specs
- [ ] Flip app to use UserPermission
- [ ] AccessRequestApprovalService writes to both join tables for time being
- [ ] Write specs to validate the above

### Guidance to review

### Checklist

- [ ] Make sure all information from the Trello card is in here
- [ ] Attach to Trello card
- [ ] Rebased master
- [ ] Cleaned commit history
- [ ] Tested by running locally

2021-12-10 10:03 UTC, dankmitchell commented
![](https://github.trello.services/images/mini-trello-icon.png) [Dual running UserPermission along with Organisation](https://trello.com/c/rRlaSz79/456-dual-running-userpermission-along-with-organisation)

2021-12-14 11:57 UTC, stellenberger commented
![](https://github.trello.services/images/mini-trello-icon.png) [(Part 4) Flip the join table and read from UserPermission](https://trello.com/c/mynYMe1O/484-part-4-flip-the-join-table-and-read-from-userpermission)

2021-12-15 11:38 UTC, malcolmbaig commented on app/services/access_request_approval_service.rb
> +    end
Need a rebase on the Part 3 branch whenever you're ready, ie—we shouldn't be seeing this code in the diff.

2021-12-15 12:14 UTC, malcolmbaig requested changes
Note - I'll continue reviewing here after the rebase

2021-12-17 11:09 UTC, darokel approved these changes

2021-12-22 10:15 UTC, malcolmbaig reviewed
LGTM - just a note that this shouldn't be merged until https://github.com/DFE-Digital/teacher-training-api/pull/2329 has been run in prod.

2021-12-23 10:48 UTC, malcolmbaig commented
In addition to rebasing, perhaps we should squash these commits too. We won't be losing much in the way of commit message detail, and it might make a revert easier to manage if we need to back this change out for whatever reason.

2022-01-05 11:17 UTC, malcolmbaig approved these changes

2022-01-05 11:18 UTC, merged