[433] Allow support users to edit the details of a course
DFE-Digital/teacher-training-api pull request #2337
Opened 2021-12-13 15:12 UTC by george-bit

### Context

As part of ongoing improvemtns to the support console, support users need the ability to update more course details than just the course code.

### Changes proposed in this pull request

This PR adds additional field to the course edit page to allow both course title and start date to be updated as well as course code.

### Guidance to review

Test in review app, plz let me know RE: any refactor.

### Checklist

- [x] Make sure all information from the Trello card is in here
- [x] Attach to Trello card
- [x] Rebased master
- [x] Cleaned commit history
- [x] Tested by running locally

2021-12-14 10:00 UTC, defong requested changes

2021-12-14 10:08 UTC, george-bit commented
![](https://github.trello.services/images/mini-trello-icon.png) [Allow support users to edit the details of a course](https://trello.com/c/7i6C5uiM/433-allow-support-users-to-edit-the-details-of-a-course)

2021-12-14 10:23 UTC, george-bit commented on app/views/support/courses/edit.html.erb
> +      <%= f.govuk_date_field(:start_date,
There can only be one...

2021-12-16 09:28 UTC, mbocc approved these changes
Tested and making changes work. Need to put in error messaging for dates, but that is already being picked up on another Trello card. Great work - thanks!

2021-12-16 09:39 UTC, merged