[447] Display and editing of ab/provider type in support UI
DFE-Digital/teacher-training-api pull request #2347
Opened 2021-12-16 15:16 UTC by george-bit

### Context

As  part of ongoing improvements to the Support Console, support users need the abilty to view and edit whether a provider is an accrediting body and their provider type

### Changes proposed in this pull request

Whilst working on this it occurred to me that  provider type has an assigned method on the  Provider model which sets the `accrediting_body` attribute. After checking with policy this is correct behaviour. This means that we only need to implement the ability to update `provider_type` via the form and then display the `accrediting_body` value on the show page.

I've added a component to disply the correct info in the correct format and andded radio buttons to the form.

new provider view:
<img width="1155" alt="image" src="https://user-images.githubusercontent.com/62567622/146397514-643fbcb0-e130-412f-965e-54b0936df143.png">

edit screen: 
<img width="1155" alt="image" src="https://user-images.githubusercontent.com/62567622/146397529-314feafb-02ed-47bf-9365-ed53830aaaf2.png">

updated record:
<img width="1155" alt="image" src="https://user-images.githubusercontent.com/62567622/146397545-e7d98625-7767-46dd-b580-534a417baf7a.png">

### Guidance to review

### Checklist

- [x] Make sure all information from the Trello card is in here
- [x] Attach to Trello card
- [x] Rebased master
- [x] Cleaned commit history
- [x] Tested by running locally

2021-12-16 15:17 UTC, george-bit commented
![](https://github.trello.services/images/mini-trello-icon.png) [Display and editing of AB in support UI](https://trello.com/c/uPhqtdog/447-display-and-editing-of-ab-in-support-ui)

2021-12-16 15:17 UTC, george-bit commented
![](https://github.trello.services/images/mini-trello-icon.png) [Display and editing of provider_type in support UI](https://trello.com/c/SmljIH6F/446-display-and-editing-of-providertype-in-support-ui)

2021-12-17 12:00 UTC, defong requested changes

2021-12-20 10:51 UTC, george-bit commented on app/views/support/providers/edit.html.erb
> +      <%= f.govuk_radio_buttons_fieldset :provider_type, legend: { text: "Provider type", size: "m" }, hint: { text: "Choosing SCITT or University will also mark Provider as an Accredited body" } do
Hey, do you mean remove the hon text and add something like:
```suggestion
      <%= f.govuk_radio_button :provider_type, :scitt, label: { text: "SCITT (Accredited body)", size: "s" }, width: 20 %>
        <%= f.govuk_radio_button :provider_type, :lead_school, label: { text: "Lead school (Not an accredited body)", size: "s" }, width: 20 %>
        <%= f.govuk_radio_button :provider_type, :university, label: { text: "University (Accredited body)", size: "s" }, width: 20 %>
```

2021-12-21 09:29 UTC, defong approved these changes
Just a minor thing

2021-12-21 09:29 UTC, defong commented on app/views/support/providers/edit.html.erb
> +        <div class="govuk-radios__divider">or</div>
```suggestion
<%= f.govuk_radio_divider %>
```

2021-12-21 10:34 UTC, mbocc approved these changes
All approved - If I click on Uni or SCITT, the Accredited Body field automatically changes to YES. If I click on Lead School, it changes to NO. 
Great work, thank you!

2021-12-21 10:35 UTC, merged