[725] Port over course salary editing functionality
DFE-Digital/teacher-training-api pull request #2535
Opened 2022-02-25 11:08 UTC by darokel

### Context

- https://trello.com/c/u4mkCREO/725-migrate-courses-course-show-page-edit-course-length-salary

### Changes proposed in this pull request

- Handle editing course length information when course is salary based as per this PR https://github.com/DFE-Digital/teacher-training-api/pull/2524/files
- DRY up shared behaviour across these two types of forms via controllers/form objects
- Increase test coverage to deal with both types in feature spec

### Guidance to review

### Checklist

- [x] Make sure all information from the Trello card is in here
- [x] Attach to Trello card
- [x] Rebased master
- [x] Cleaned commit history
- [x] Tested by running locally

2022-02-25 11:09 UTC, darokel commented
![](https://github.trello.services/images/mini-trello-icon.png) [Migrate Courses - Course show page - edit course length & salary](https://trello.com/c/u4mkCREO/725-migrate-courses-course-show-page-edit-course-length-salary)

2022-02-28 15:40 UTC, goodviber approved these changes
LGTM, maybe have Sau have a look incase I am missing some context?

2022-02-28 17:28 UTC, defong requested changes

2022-02-28 17:28 UTC, defong commented on app/views/publish/courses/_course_length_field.html.erb
> +<% end %>
newline please

2022-02-28 17:28 UTC, defong commented on app/views/publish/courses/salary/edit.html.erb
> +<% page_title = "Course length and fees" %>
```suggestion
<% page_title = "Course length and salary" %>
```

![image](https://user-images.githubusercontent.com/470137/156029829-ce2e239d-0eba-4087-acbb-ca45a9f74476.png)

2022-03-01 12:41 UTC, defong approved these changes

2022-03-01 13:11 UTC, merged