Remove provider personas when going to support
DFE-Digital/teacher-training-api pull request #2756
Opened 2022-06-16 11:20 UTC by avinhurry

### Context

`/support` leads us to support login. For personas (on qa and dev environments) we have 3 personas that are not eligible to login. These personas are for publish, not support. 

### Changes proposed in this pull request

### Guidance to review

### Checklist

- [ ] Make sure all information from the Trello card is in here
- [ ] Attach to Trello card
- [ ] Rebased main
- [ ] Cleaned commit history
- [ ] Tested by running locally

2022-06-16 11:24 UTC, avinhurry commented
![](https://github.trello.services/images/mini-trello-icon.png) [Publish - Remove provider personas when going to support](https://trello.com/c/ovgt9xml/131-publish-remove-provider-personas-when-going-to-support)

2022-06-16 11:26 UTC, avinhurry commented
![](https://github.trello.services/images/mini-trello-icon.png) [Publish - Remove provider personas when going to support](https://trello.com/c/ovgt9xml/131-publish-remove-provider-personas-when-going-to-support)

2022-06-17 10:03 UTC, SamJamCul requested changes

2022-06-17 10:03 UTC, SamJamCul commented on app/controllers/concerns/authentication.rb
> +      redirect_to sign_in_path({ support: params[:controller].start_with?("support") })
Discussed on slack, would be good to only populate this param if we're in dev or qa, as it's non-functional in prod

2022-06-17 15:38 UTC, SamJamCul approved these changes

2022-06-17 15:42 UTC, merged